# Generated by Django 2.2.10 on 2020-09-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Файл с данными'),
        ),
    ]
