# Generated by Django 2.2.10 on 2020-10-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_shop_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.FileField(upload_to='fixtures/'),
        ),
    ]
